version '3.0'
services:
  serve:
    build: .
    volumes:
      - /home/radone/RedMongo
    ports:
      - "5000:5000"
      environment:
        APP_NAME: 'helloservlet'
        APP_CLASS: 'mypkg'
      command: ["run.sh"]